import React,{useEffect,useState} from "react";
import {Search,ShoppingCart,Star,SlidersHorizontal} from "lucide-react";
import {useDispatch} from "react-redux";
import {addToCart} from "../redux/cartSlice";
import api from "../lib/api";
import {toast} from "sonner";

const Products=()=>{const [products,setProducts]=useState([]),[search,setSearch]=useState(""),[category,setCategory]=useState("All"),[loading,setLoading]=useState(true);const dispatch=useDispatch();
useEffect(()=>{let x;const run=async()=>{setLoading(true);try{x=await api.get('/products',{params:{search,category}});setProducts(x.data.products)}catch(e){toast.error('Unable to load products')}finally{setLoading(false)}};const t=setTimeout(run,250);return()=>clearTimeout(t)},[search,category]);
const cats=["All",...new Set(products.map(p=>p.category))];return <div className="min-h-screen bg-slate-50 pt-28 pb-16"><div className="max-w-7xl mx-auto px-4"><div className="flex flex-col md:flex-row md:items-end justify-between gap-5 mb-8"><div><p className="text-sm font-semibold text-blue-600">MANOJMART STORE</p><h1 className="text-4xl md:text-5xl font-black tracking-tight mt-1">Shop the latest.</h1><p className="text-slate-500 mt-2">Curated tech, transparent prices, fast checkout.</p></div><div className="relative w-full md:w-80"><Search className="absolute left-3 top-3.5 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..." className="w-full h-11 pl-10 pr-4 rounded-xl border bg-white outline-none focus:ring-2 focus:ring-blue-500"/></div></div><div className="flex gap-2 overflow-x-auto pb-3 mb-6">{cats.map(c=><button key={c} onClick={()=>setCategory(c)} className={`px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${category===c?'bg-slate-950 text-white':'bg-white border text-slate-600 hover:bg-slate-100'}`}>{c}</button>)}</div>{loading?<div className="grid md:grid-cols-3 lg:grid-cols-4 gap-5">{[1,2,3,4].map(i=><div key={i} className="h-80 bg-white rounded-2xl animate-pulse"/>)}</div>:products.length===0?<div className="py-24 text-center"><SlidersHorizontal className="mx-auto text-slate-300"/><p className="mt-3 text-slate-500">No products found.</p></div>:<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{products.map(p=><div key={p._id} className="group bg-white rounded-2xl border overflow-hidden hover:shadow-xl hover:-translate-y-1 transition-all"><div className="aspect-square bg-slate-100 p-5"><img src={p.image||'/favicon.svg'} alt={p.name} className="w-full h-full object-contain mix-blend-multiply group-hover:scale-105 transition"/></div><div className="p-4"><div className="flex justify-between gap-2"><span className="text-xs text-blue-600 font-semibold">{p.category}</span><span className="flex items-center gap-1 text-xs"><Star className="w-3 h-3 fill-current"/>{p.rating}</span></div><h3 className="font-bold mt-2 line-clamp-1">{p.name}</h3><p className="text-xs text-slate-500 mt-1 line-clamp-2">{p.description}</p><div className="flex items-center justify-between mt-4"><div><span className="font-black text-lg">₹{p.price.toLocaleString('en-IN')}</span>{p.originalPrice>p.price&&<del className="ml-2 text-xs text-slate-400">₹{p.originalPrice.toLocaleString('en-IN')}</del>}</div><button onClick={()=>{dispatch(addToCart(p));toast.success('Added to cart')}} className="w-10 h-10 rounded-xl bg-slate-950 text-white flex items-center justify-center hover:bg-blue-600"><ShoppingCart className="w-4 h-4"/></button></div></div></div>)}</div>}</div></div>};export default Products;
