import React,{useEffect,useRef,useState} from "react";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {User,Mail,Phone,MapPin,Package,CheckCircle2,Clock3,Camera} from "lucide-react";
import {useDispatch,useSelector} from "react-redux"; import {setUser} from "../redux/userSlice"; import api from "../lib/api"; import {toast} from "sonner"; import {useSearchParams} from "react-router-dom";

const compressImage=file=>new Promise((resolve,reject)=>{const img=new Image();const reader=new FileReader();reader.onload=()=>{img.onload=()=>{const max=500,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)});
export default function Profile(){const user=useSelector(s=>s.user.user),dispatch=useDispatch(),[params,setParams]=useSearchParams(),[orders,setOrders]=useState([]),[saving,setSaving]=useState(false),fileRef=useRef();const [form,setForm]=useState({firstName:user?.firstName||'',lastName:user?.lastName||'',email:user?.email||'',phoneNo:user?.phoneNo||'',address:user?.address||'',city:user?.city||'',zipCode:user?.zipCode||'',profilePic:user?.profilePic||''});
 useEffect(()=>{if(user)setForm(f=>({...f,firstName:user.firstName||'',lastName:user.lastName||'',email:user.email||'',phoneNo:user.phoneNo||'',address:user.address||'',city:user.city||'',zipCode:user.zipCode||'',profilePic:user.profilePic||''}))},[user]);
 useEffect(()=>{if(user)api.get('/orders/my').then(r=>setOrders(r.data.orders||[])).catch(()=>{})},[user]);
 const save=async e=>{e.preventDefault();setSaving(true);try{const r=await api.put('/user/profile',form);dispatch(setUser(r.data.user));toast.success('Profile updated successfully')}catch(e){toast.error(e.response?.data?.message||'Profile update failed')}finally{setSaving(false)}};
 const photo=async e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return toast.error('Please select an image');if(f.size>5*1024*1024)return toast.error('Image must be under 5MB');try{setForm({...form,profilePic:await compressImage(f)});toast.success('Photo selected. Click Update Profile to save.')}catch{toast.error('Could not process image')}};
 if(!user)return <div className="min-h-screen pt-32 text-center">Please login to view your profile.</div>;
 return <div className="pt-28 min-h-screen bg-slate-50 pb-16"><Tabs defaultValue={params.get('tab')==='orders'?'orders':'profile'} className="max-w-5xl mx-auto px-4"><div className="flex justify-center mb-6"><TabsList className="bg-white border shadow-sm rounded-xl p-1"><TabsTrigger value="profile" className="px-8">Profile</TabsTrigger><TabsTrigger value="orders" className="px-8">Orders</TabsTrigger></TabsList></div>
 <TabsContent value="profile"><div className="bg-white border rounded-3xl overflow-hidden shadow-sm"><div className="h-36 bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600"/><div className="px-6 md:px-8 pb-8"><div className="-mt-14 flex items-end justify-between"><div className="relative w-28 h-28 rounded-full bg-white p-1 shadow-xl"><div className="w-full h-full rounded-full bg-slate-100 overflow-hidden flex items-center justify-center">{form.profilePic?<img src={form.profilePic} className="w-full h-full object-cover"/>:<User className="w-12 h-12 text-slate-400"/>}</div><button type="button" onClick={()=>fileRef.current?.click()} className="absolute right-0 bottom-0 w-9 h-9 rounded-full bg-slate-950 text-white flex items-center justify-center border-4 border-white"><Camera size={16}/></button><input ref={fileRef} hidden type="file" accept="image/*" onChange={photo}/></div><span className="mb-3 px-3 py-1 rounded-full bg-green-50 text-green-700 text-xs font-semibold">{user.role==='admin'?'Administrator':'Account active'}</span></div>
 <h1 className="text-2xl font-black mt-5">My Profile</h1><p className="text-slate-500 text-sm mt-1">Update your account, delivery details and profile photo.</p>
 <form onSubmit={save} className="grid md:grid-cols-2 gap-5 mt-7">{[['firstName','First Name',User],['lastName','Last Name',User],['email','Email',Mail],['phoneNo','Phone',Phone],['address','Address',MapPin],['city','City',MapPin],['zipCode','ZIP Code',MapPin]].map(([n,l,I])=><div key={n} className={n==='address'?'md:col-span-2':''}><label className="text-sm font-semibold mb-2 block">{l}</label><div className="relative"><I className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input name={n} type={n==='email'?'email':'text'} value={form[n]} onChange={e=>setForm({...form,[n]:e.target.value})} className="w-full h-11 pl-10 pr-3 rounded-xl border outline-none focus:ring-2 focus:ring-blue-500"/></div></div>)}<button disabled={saving} className="md:col-span-2 bg-slate-950 text-white rounded-xl py-3 font-bold hover:bg-blue-600 transition">{saving?'Saving...':'Update Profile'}</button></form></div></div></TabsContent>
 <TabsContent value="orders"><div className="space-y-5"><div className="bg-slate-950 text-white rounded-3xl p-7"><p className="text-blue-300 text-sm font-semibold">MANOJMART ORDERS</p><h1 className="text-3xl font-black mt-1">Track your orders</h1></div>{orders.length===0?<div className="bg-white rounded-3xl border p-14 text-center"><Package className="mx-auto text-slate-300 w-12 h-12"/><p className="font-bold mt-4">No orders yet</p></div>:orders.map(o=><div key={o._id} className="bg-white border rounded-3xl overflow-hidden"><div className="p-5 border-b flex flex-wrap gap-6 justify-between"><div><p className="text-xs text-slate-400">ORDER ID</p><b>#{String(o._id).slice(-8).toUpperCase()}</b></div><div><p className="text-xs text-slate-400">DATE</p><span>{new Date(o.createdAt).toLocaleDateString('en-IN')}</span></div><div><p className="text-xs text-slate-400">TOTAL</p><b>₹{Number(o.amount).toLocaleString('en-IN')}</b></div><span className="h-fit px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-bold">{o.status}</span></div><div className="p-5 space-y-4">{o.items.map((i,idx)=><div key={idx} className="flex gap-4"><img src={i.image} className="w-16 h-16 rounded-xl bg-slate-50 object-contain"/><div><b>{i.name}</b><p className="text-sm text-slate-500">Qty {i.quantity} · ₹{i.price}</p></div></div>)}</div><div className="p-5 bg-slate-50 border-t"><div className="grid sm:grid-cols-3 md:grid-cols-6 gap-4">{['Placed','Confirmed','Processing','Shipped','Out for Delivery','Delivered'].map((s,i)=>{const done=['Placed','Confirmed','Processing','Shipped','Out for Delivery','Delivered'].indexOf(o.status)>=i;return <div key={s} className="flex items-center gap-2"><div className={`w-8 h-8 rounded-full flex items-center justify-center ${done?'bg-green-500 text-white':'bg-white text-slate-300 border'}`}>{done?<CheckCircle2 className="w-4"/>:<Clock3 className="w-4"/>}</div><span className={`text-xs font-semibold ${done?'text-slate-700':'text-slate-400'}`}>{s}</span></div>})}</div></div></div>)}</div></TabsContent></Tabs></div>}
